### ISSUE TITLE
No Directory: input/song.txt

### ISSUE THREAD

**Issue by kalpshah18** [Aditya-Khadilkar/Music-Synth#2]
Traceback (most recent call last):
  File "master.py", line 15, in <module>
    convert2abc(song)
  File "C:\Users\vertex\Documents\Python\Music-Synth\mid2abc.py", line 10, in convert2abc
    f = open('input/song.txt', 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'input/song.txt'

**Comment by Aditya-Khadilkar** [comment]
I have pushed another version. Ideally it should just create a new folder called input, but oh well  ¯\_(ツ)_/¯
clone it again and check :)
